host: ${MIKROTIKE_HOST}
username: ${MIKROTIK_USERNAME}
password: ${NIKROTIK_PASSWORD}

# --- AI Configuration ---
ai_provider: gemini
openai_api_key: ${OPENAI_API_KEY}
gemini_api_key: ${GEMINI_API_KEY}
gemini_model: "gemini-2.5-pro"
openai_model: "gpt-4-turbo"


ai_prompt: >
  You are a senior network security and performance analyst. Your task is to provide a comprehensive and actionable analysis of a network device using the following data. Your response must be structured with the headings provided below.

  **Device Data:**
  - MAC: {mac}
  - IP: {ip}
  - Hostname: {hostname}
  - Label: {comment}
  - Vendor: {vendor}
  - Interface: {interface}
  - Device Type: {description}
  - Status: {status}
  - Static: {static}
  - Last Seen: {last_seen}
  - User Notes: {notes}

  **Analysis & Recommendations:**

  **1. Executive Summary:**
  Provide a detailed, plain-English summary of what this device is.

  **2. Security Assessment:**
  Analyze the device from a security perspective.

  **3. Configuration Recommendation:**
  - **Static IP:** State "Yes" or "No". Justify your answer.
  - **Device Label:** Suggest an improved, descriptive label.

  **4. Housekeeping Action:**
  Recommend a single, clear action: KEEP, INVESTIGATE, or REMOVE.

  **5. Confidence Score:**
  Provide a score from 1 to 5 and briefly explain your reasoning.
  
  ---COMMANDS---
  
  **6. Actionable Commands:**
  
  **Warning:** Only execute these commands if you understand their purpose and how to use them. Misuse can interrupt network functionality.
  
  **RULES FOR GENERATING COMMANDS:**
  - **NEVER** use backticks, asterisks, or any markdown formatting for the commands.
  - **EACH COMMAND MUST BE ON ITS OWN SEPARATE LINE.**
  
  - **IF** your recommendation in section 4 is 'REMOVE', THEN ONLY generate this single, exact line:
  `python3 dhcp_sage.py --mac {mac} --delete`
  
  - **ELSE (if the recommendation is not REMOVE):**
    - **IF** the 'Static' status in the data is 'no' AND your recommendation in section 3 was 'Yes', THEN generate this exact line:
    `python3 dhcp_sage.py --mac {mac} --set-static`
    
    - **IF** you suggested a new 'Device Label' in section 3 that is different from the current 'Label', THEN generate this exact line:
    `python3 dhcp_sage.py --mac {mac} --comment "Your new suggested label"`
